apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksboot
  region: us-west-2

nodeGroups:
  - name: ng-1
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]